services:
  - type: web
    name: reliefchain-ai
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:///./reliefchain.db
      - key: STORAGE_PATH
        value: ./storage/uploads
      - key: MST_RPC_URL
        value: https://testnetrpc.mstblockchain.com
      - key: MST_CONTRACT_ADDRESS
        value: 0x6c630C62D7D12CDf8a2BfEaa7995F1ce2D3937D2
      - key: MST_EXPLORER_URL
        value: https://mstscan.com
